### ISSUE TITLE
calc_derived_2cpt seems not to accept Q2 as synonym for Q

### ISSUE THREAD

**Issue by bergsmat** [kestrel99/pmxTools#15]
Thanks for a great set of tools! 

At version 1.0, for calc_derived(), I see the example
```
calc_derived_2cpt(CL=16, V1=25, V2=50, Q=0.5)
```
which works as expected, but I only get partial results for
```
calc_derived_2cpt(CL=16, V1=25, V2=50, Q2=0.5)
```
The help indicates Q2 and Q are synonyms.  Indeed, all other uses of synonyms seem to work.

**Comment by billdenney** [comment]
Good catch!  This was recently fixed in 6fceb495519e53b5caedbab9b0520f57fd0b3ef2.
