### ISSUE TITLE
ka and tlag returned even if not supplied to calc_derived()

### ISSUE THREAD

**Issue by bergsmat** [kestrel99/pmxTools#16]
Hi again.

The help for calc_derived() indicates that lag (actually, tlag) and ka will be returned if provided.  I'm seeing them as list members with value NULL even when not supplied.  I suggest, drop them, or if necessary return them with as NA with length like other members so that the following succeeds:
```
 as.data.frame(calc_derived_1cpt(CL=16, V=25))
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0
```
Thanks for considering!

**Comment by billdenney** [comment]
I tend to prefer `NA` and `NULL` indicating different things where `NA` would indicate that calculation was attempted but resulted in missing for some reason while `NULL` indicates that calculation was not attempted.  That said, I view this as more of Justin's call.

**Comment by kestrel99** [comment]
Sorry for the late response. calc_derived() now does not return NULL parameters.
