### ISSUE TITLE
documentation for argument 'type' in calc_derived() is unclear

### ISSUE THREAD

**Issue by bergsmat** [kestrel99/pmxTools#17]
Hi again.  calc_derived() seems really useful.  I'm having trouble with argument type='all'.  The main documentation says "see details" but there is no section by that name (v. 1.0) and I did not see further discussion below.  By the way, I see units L and h etc. in the documentation for the output which likely are appropriate for most cases but not essential to the calculations.

**Comment by billdenney** [comment]
Good points.  I just made a PR to clarify these points in the docs.
