### ISSUE TITLE
calc_derived: feature request for micro parameter interface

### ISSUE THREAD

**Issue by bergsmat** [kestrel99/pmxTools#18]
I love the generality of calc_derived(), thanks!  

Looking at internals, it seems that macro parameters are converted to micro parameters which are then used to solve the system.  In my use case, I already have the micro parameters k10, k12, k21 etc so I end up converting these to macros which then calc_derived converts back to micros. Perhaps pmxTools could export a micro interface which both calc_derived() and the user could call.  Maybe it's more complicated than that since most users of the micro interface would probably want the macro parameters back-calculated as well. "Clearinghouse" interface?

**Comment by billdenney** [comment]
When I did the rewrite of `calc_derived()` I debated allowing a combination of micro and macro parameters.  The main challenge that gave me pause is how should they be handled?  Should it be required that the user only give one set or the other, and what if they give a mixture (e.g. `k10` with `CL` can calculate `V`, and `k10` with `V` can calculate `CL`).  When I thought of the possibility of those mixed parameters being provided, it then got to the complexity of what tolerance is required for similarity between parameters that could be calculated multiple ways or when redundant parameters are provided.  It got messy.

I think that if you were interested in making a PR for a "micro or macro but cannot mix the two" interface, that would be a great contribution.

**Comment by mattfidler** [comment]
FYI: This functionality will be available in the next release `RxODE` since the calculations were already performed with the `linCmt()`;  It also takes data-frames and output data-frames.  

``` r
library(RxODE)

rxDerived(V=10,k10=3)
#>   vc kel vss cl  t12alpha alpha   A fracA
#> 1 10   3  10 30 0.2310491     3 0.1     1

rxDerived(V=10,Cl=3)
#>   vc kel vss cl t12alpha alpha   A fracA
#> 1 10 0.3  10  3 2.310491   0.3 0.1     1

rxDerived(V1=10, k10=3)
#>   vc kel vss cl  t12alpha alpha   A fracA
#> 1 10   3  10 30 0.2310491     3 0.1     1

rxDerived(V1=10, k10=2:3)
#>   vc kel vss cl  t12alpha alpha   A fracA
#> 1 10   2  10 20 0.3465736     2 0.1     1
#> 2 10   3  10 30 0.2310491     3 0.1     1

rxDerived(data.frame(V=10,k10=3:4))
#>   vc kel vss cl  t12alpha alpha   A fracA
#> 1 10   3  10 30 0.2310491     3 0.1     1
#> 2 10   4  10 40 0.1732868     4 0.1     1
```

<sup>Created on 2020-07-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It would easy to put a pull request that depends on RxODE, but I'm unsure that is warranted.

**Comment by bergsmat** [comment]
Happy to table this pending next release of RxODE.
