### ISSUE TITLE
pmxTools not loading 

### ISSUE THREAD

**Issue by mjbrooklyn** [kestrel99/pmxTools#22]
Hi,  when loading pmxTools, I get a  error message

compilation terminated.
make: *** [C:/PROGRA~1/R/R-3.5.3/etc/i386/Makeconf:208: feedback_arc_set.o] Error 1
ERROR: compilation failed for package 'igraph'
* removing 'C:/Users/m5san/Documents/R/win-library/3.5/igraph'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status
ERROR: dependency 'igraph' is not available for package 'DiagrammeR'
* removing 'C:/Users/m5san/Documents/R/win-library/3.5/DiagrammeR'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘DiagrammeR’ had non-zero exit status
ERROR: dependency 'DiagrammeR' is not available for package 'pmxTools'
* removing 'C:/Users/m5san/Documents/R/win-library/3.5/pmxTools'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘pmxTools’ had non-zero exit status

Thanks
Marty

**Comment by billdenney** [comment]
@mjbrooklyn , Can you please share the command that you ran and the full output from that?

It looks like you were trying to install pmxTools on Windows.  And, it appears that the underlying is related to trying to install the `igraph` library.

**Comment by mjbrooklyn** [comment]
I was using Rstudio and installed the package from CRAN

**Comment by billdenney** [comment]
I'm not exactly sure what the issue is, but the version of R that you're running is old.  I would start by updating to the current version of R (and Rstudio, if applicable), and retrying.

**Comment by mjbrooklyn** [comment]
Updated to R 4.02.  igraph package still not loading - non zero exit status

**Comment by mjbrooklyn** [comment]
I was able to pmxTools working on a Mac. Had to update xcode, command line
tools and  rlang for it to work.

**Comment by billdenney** [comment]
Great!
