### ISSUE TITLE
Reading is not working for the `mapbayr` example

### ISSUE THREAD

**Issue by mattfidler** [kestrel99/pmxTools#28]
I was using the example NONMEM files at:

https://github.com/FelicienLL/mapbayr-CPTPSP-2021

Specifically at:

https://github.com/FelicienLL/mapbayr-CPTPSP-2021/blob/main/nonmem%20output/run001.zip

And noticed that `run1.mod` had `42000` records but the input dataset had `18000` records (as shown in the nonmem `.lst` output).  

I think that the `pmxTools::read_nm_multi_table` is not working correctly.

It has a custom format in the nomem file, but in theory that shouldn't affect it.

**Comment by mattfidler** [comment]
It also wasn't working with the following example:

https://github.com/philipdelff/NMdata/blob/4aa56c77544b8fccb7944ebd4b0c6df75606657a/inst/examples/nonmem/xgxr001.mod

That being said, `NMdata::NMreadTab` worked perfectly.  

Perhaps import/replace this particular function.  I will have to check to see if it works with the mapbayr example.

They have over 80% coverage in their examples too, so you could possibly use that to check against.

**Comment by kestrel99** [comment]
Checked with run001.tab in https://github.com/FelicienLL/mapbayr-CPTPSP-2021/blob/main/nonmem%20output/run001.zip:

```
tab <- read_nm_multi_table("run001.tab")
nrow(tab)   # 18000
```

I confirm the issue with the NMData example: the NONMEM output table repeats the column headers for no apparent reason towards the end of the file, resulting in all data being imported as character type, and one extra row of garbage. I have pushed a fix which checks for stray text in NONMEM output imported by `pmxTools::read_nm_multi_table()` and `pmxTools::read_nmtable_single()` and removes it.

**Comment by mattfidler** [comment]
Thanks @kestrel99
